### ISSUE TITLE
word should include '-' char

### ISSUE THREAD

**Issue by weijarz** [alexchee/atom-inline-autocomplete#16]
for this code:
```bash
#!/bin/bash
file-name=foo
file-path=bar
```

when trigger on 'file', it should include 'file-name'

**Comment by alexchee** [comment]
good idea

**Comment by alexchee** [comment]
version 1.0.1 should now include '-' and '_' in the words.

**Comment by alexchee** [comment]
Actually this still doesn't work because I use `cursor.selectWord()` to highlight the word to replace. This needs to be a setting change to remove '-' from nonWordCharacters. 

There's a discussion here https://discuss.atom.io/t/append-to-default-nonwordcharacters-in-settings/11590/5
and an issue about it here https://github.com/atom/settings-view/issues/243
